## Server Properties
server:
  port: 5000

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testapp?serverTimezone=UTC
    username: aramis_user
    password: aramis_00
    # Initialize the datasource with available DDL and DML scripts
    initialization-mode=always: always
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
## Jackson Properties
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

#Hibernate logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

## App Properties
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
